const KEY='executive-calendar-v1',SETTINGS_KEY='executive-calendar-settings-v1',LAST_BACKUP_KEY='executive-calendar-last-backup-v1',START=9,END=23,SLOTS=Array.from({length:(END-START)*4+1},(_,i)=>`${String(START+Math.floor(i/4)).padStart(2,'0')}:${String(i%4*15).padStart(2,'0')}`),DEFAULT_SETTINGS={timeStart:'09:00',timeEnd:'23:00',slotMinutes:15,sundayScheduling:false};
let events=JSON.parse(localStorage.getItem(KEY)||'[]'),anchor=localISO(new Date()),rangeEnd=addDays(localISO(new Date()),20),search='';const $=id=>document.getElementById(id);
function localISO(d){const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)}function date(d){return new Date(d+'T00:00:00')}function addDays(d,n){const x=date(d);x.setDate(x.getDate()+n);return localISO(x)}function min(t){const[a,b]=t.split(':').map(Number);return a*60+b}function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function save(){localStorage.setItem(KEY,JSON.stringify(events))}function settings(){return{...DEFAULT_SETTINGS,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}}function isSunday(d){return date(d).getDay()===0}function weekday(d){return new Intl.DateTimeFormat('zh-CN',{weekday:'long'}).format(date(d))}function download(text,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),2500)}function eventClass(v){return v>=5?'v5':v===4?'v4':v<=2?'v'+v:''}function formatDay(d,year=true){return new Intl.DateTimeFormat('zh-CN',{year:year?'numeric':undefined,month:'long',day:'numeric',weekday:'long'}).format(date(d))}
function drawEvent(e){const len=(min(e.end)-min(e.start))/15;return `<article class="event ${eventClass(+e.value)}" data-id="${e.id}" style="width:calc(${len*100}% - 6px)"><strong>${esc(e.title)}</strong><span>${e.start}–${e.end}${e.location?' · '+esc(e.location):''}</span></article>`}
function render(){let n=Math.round((date(rangeEnd)-date(anchor))/86400000);if(n<0){rangeEnd=anchor;n=0}if(n>90){n=90;rangeEnd=addDays(anchor,n)}const days=Array.from({length:n+1},(_,i)=>addDays(anchor,i));$('datePicker').value=anchor;$('endPicker').value=rangeEnd;$('rangeLabel').textContent=`${formatDay(days[0],false)} — ${formatDay(days.at(-1),false)}`;const last=localStorage.getItem(LAST_BACKUP_KEY);$('lastBackup').textContent=last?`最后备份：${new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(last))}`:'最后备份：尚未备份';const q=search.trim().toLowerCase(),visible=events.filter(e=>!q||[e.title,e.type,e.people,e.location,e.notes].join(' ').toLowerCase().includes(q));let h='<div class="grid"><div class="corner">日期 / 时间</div>'+SLOTS.map((t,i)=>`<div class="time-head">${t}<em>${i%4===0?'整点':''}</em></div>`).join('');for(const d of days){const sun=isSunday(d),ds=visible.filter(e=>e.date===d);h+=`<div class="date-cell ${sun?'sunday':''}"><strong>${formatDay(d,false)}</strong><span>${sun?'休息日 · 禁止排程':'点击时间格快速新增'}</span></div>`;for(let i=0;i<SLOTS.length;i++){const terminal=i===SLOTS.length-1,t=SLOTS[i],items=!terminal&&!sun?ds.filter(e=>e.start===t):[];h+=`<div class="slot ${sun||terminal?'disabled':''}" data-date="${d}" data-time="${t}">${items.map(drawEvent).join('')}</div>`}}$('scheduleGrid').innerHTML=h+'</div>';document.querySelectorAll('.event').forEach(x=>x.onclick=e=>{e.stopPropagation();openEdit(x.dataset.id)});document.querySelectorAll('.slot:not(.disabled)').forEach(x=>x.onclick=()=>openNew(x.dataset.date,x.dataset.time))}
function fillTimes(){$('startTime').innerHTML=SLOTS.slice(0,-1).map(x=>`<option>${x}</option>`).join('');$('endTime').innerHTML=SLOTS.slice(1).map(x=>`<option>${x}</option>`).join('')}
function openNew(d=anchor,t='09:00'){if(isSunday(d)){toast('星期日禁止安排日程，请选择工作日。');return}$('eventForm').reset();$('eventId').value='';$('eventDate').value=d;$('startTime').value=t;$('endTime').value=SLOTS[Math.min(SLOTS.indexOf(t)+4,SLOTS.length-1)];$('eventPrepTime').value=0;$('formMode').textContent='新建日程';$('deleteBtn').hidden=true;$('formAlert').textContent='';$('eventDialog').showModal()}
function openEdit(id){const e=events.find(x=>x.id===id);if(!e)return;for(const k of ['Id','Date','Title','Type','People','Location','Value','Attendance','Notes'])$('event'+k).value=e[k.toLowerCase()]??(k==='Id'?e.id:'');$('eventPrepTime').value=e.prepTime??0;$('startTime').value=e.start;$('endTime').value=e.end;$('formMode').textContent='编辑日程';$('deleteBtn').hidden=false;$('formAlert').textContent='';$('eventDialog').showModal()}
function check(e){if(isSunday(e.date))return '星期日禁止安排日程。';if(min(e.start)>=min(e.end))return '结束时间必须晚于开始时间。';const c=events.find(x=>x.id!==e.id&&x.date===e.date&&min(e.start)<min(x.end)&&min(e.end)>min(x.start));return c?`与「${c.title}」（${c.start}–${c.end}）时间冲突。`:''}
$('eventForm').onsubmit=x=>{x.preventDefault();const e={id:$('eventId').value||String(Date.now()),date:$('eventDate').value,title:$('eventTitle').value.trim(),start:$('startTime').value,end:$('endTime').value,type:$('eventType').value.trim(),people:$('eventPeople').value.trim(),location:$('eventLocation').value.trim(),value:+$('eventValue').value,attendance:$('eventAttendance').value,prepTime:+$('eventPrepTime').value||0,notes:$('eventNotes').value.trim()},err=check(e);if(err){$('formAlert').textContent=err;return}const i=events.findIndex(x=>x.id===e.id);i<0?events.push(e):events[i]=e;save();$('eventDialog').close();render();toast(i<0?'日程已新增':'日程已更新')};
$('addBtn').onclick=()=>openNew();$('todayBtn').onclick=()=>{anchor=localISO(new Date());rangeEnd=addDays(anchor,20);render()};$('prevBtn').onclick=()=>{const n=Math.round((date(rangeEnd)-date(anchor))/86400000)+1;anchor=addDays(anchor,-n);rangeEnd=addDays(rangeEnd,-n);render()};$('nextBtn').onclick=()=>{const n=Math.round((date(rangeEnd)-date(anchor))/86400000)+1;anchor=addDays(anchor,n);rangeEnd=addDays(rangeEnd,n);render()};$('datePicker').onchange=e=>{anchor=e.target.value;render()};$('endPicker').onchange=e=>{rangeEnd=e.target.value;render()};$('searchInput').oninput=e=>{search=e.target.value;render()};$('closeDialog').onclick=$('cancelBtn').onclick=()=>$('eventDialog').close();$('deleteBtn').onclick=()=>{const id=$('eventId').value;if(confirm('确定删除此日程吗？')){events=events.filter(e=>e.id!==id);save();$('eventDialog').close();render();toast('日程已删除')}};
$('exportBtn').onclick=()=>{const cols=['日期','星期','开始时间','结束时间','事项名称','参与人员','地点','重要等级','是否必须参加','备注'],rows=events.map(e=>[e.date,weekday(e.date),e.start,e.end,e.title,e.people,e.location,e.value,e.attendance,e.notes]),csv='\uFEFF'+[cols,...rows].map(r=>r.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(',')).join('\n');download(csv,'总经理日程查看表.csv','text/csv;charset=utf-8')};
$('backupBtn').onclick=()=>{const now=new Date(),backup={schemaVersion:1,application:'总经理日程管理与时间规划工具',exportedAt:now.toISOString(),settings:settings(),calendar:{rangeStart:anchor,rangeEnd,dates:[...new Set(events.map(e=>e.date))].sort().map(d=>({date:d,weekday:weekday(d)}))},events};download(JSON.stringify(backup,null,2),`总经理日程完整备份-${localISO(now)}.json`,'application/json;charset=utf-8');localStorage.setItem(LAST_BACKUP_KEY,now.toISOString());render();toast('完整备份文件已生成')};
$('restoreInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!Array.isArray(data.events))throw 0;if(!confirm(`确定恢复此备份中的 ${data.events.length} 条日程吗？当前本地数据将被替换。`))return;events=data.events;localStorage.setItem(SETTINGS_KEY,JSON.stringify({...DEFAULT_SETTINGS,...(data.settings||{})}));if(data.calendar?.rangeStart)anchor=data.calendar.rangeStart;if(data.calendar?.rangeEnd)rangeEnd=data.calendar.rangeEnd;save();localStorage.setItem(LAST_BACKUP_KEY,new Date().toISOString());render();toast(`已恢复 ${events.length} 条日程与系统设置`)}catch{toast('导入失败：请选择本工具导出的 JSON 备份文件。')}};r.readAsText(f,'utf-8');e.target.value=''};
$('importInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const rows=String(r.result).replace(/^\uFEFF/,'').trim().split(/\r?\n/).slice(1).map(l=>[...l.matchAll(/(?:^|,)(?:"((?:[^"]|"")*)"|([^,]*))/g)].map(m=>(m[1]??m[2]).replaceAll('""','"'))).map(a=>({id:String(Date.now()+Math.random()),date:a[0],start:a[2]||a[1],end:a[3]||a[2],title:a[4]||a[3],type:'',people:a[5]||a[4],location:a[6]||a[5],value:+(a[7]||a[6])||3,attendance:a[8]||a[7]||'可授权',prepTime:0,notes:a[9]||a[8]||''})).filter(x=>x.date&&x.title&&x.start&&x.end);events.push(...rows);save();render();toast(`已导入 ${rows.length} 条日程`)}catch{toast('导入失败：请使用本工具导出的 CSV 格式。')}};r.readAsText(f,'utf-8');e.target.value=''};
$('clearBtn').onclick=()=>{if(confirm('确定清空全部本地日程吗？')){events=[];save();render()}};fillTimes();render();
